services:
  postgres:
    image: postgres:17
    container_name: dbserver
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pg123"
      POSTGRES_DB: "primarydb"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal
    
  api:
    image: cecilieelkjaer/minitwit-api:latest
    build:
      context: .
      dockerfile: src/Chirp.Api/Dockerfile
    container_name: apiserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ENV ASPNETCORE_URLS="http://+:5000"
      - ENV DOTNET_RUNNING_IN_CONTAINER="true"
      - ConnectionStrings__DefaultConnection=Host=dbserver;Database=primarydb;Username=postgres;Password=pg123
    volumes:
      - dataprotection_keys:/app/keys
    ports:
      - "5000:8080"
    depends_on:
      postgres: 
        condition: service_healthy
    networks:
      - internal

  web:
    image: cecilieelkjaer/minitwit-web:latest
    build:
      context: .
      dockerfile: src/Chirp.Web/Dockerfile
    container_name: webserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ENV ASPNETCORE_URLS="http://+:5000"
      - ENV DOTNET_RUNNING_IN_CONTAINER="true"
      - ConnectionStrings__DefaultConnection=Host=dbserver;Database=primarydb;Username=postgres;Password=pg123
    volumes:
      - dataprotection_keys:/app/keys
    ports:
      - "5001:8080"
    depends_on:
      postgres: 
        condition: service_healthy
    networks:
      - internal

volumes:
  postgres_data:
  dataprotection_keys:

networks:
  internal:
    driver: bridge
    name: internal
    
